export let DOMAIN = "http://0.0.0.0:1234"
export let LOGIN = '/api/user/login'
export let REGISTER = "/api/user/register"
export let PROFILE = "/api/user/me"
export let UPDATE_PROFILE = "/api/user/update-profile"
export let UPDATE_PASSWORD = "/api/user/update-password"
export let FIND_ONE = "/api/user/find-one?id="
export let GET_ONE_USER = '/api/admin/get-one-user'
export let GET_ALL_USER = '/api/admin/get-all-user'
export let SEARCH = '/api/search'
export let SUBCRIBE = '/api/follow/subcribe?publisher='
export let GET_FOLLOWERS = '/api/follow/get-followers?username='
export let GET_MIN_FOLLOWERS = '/api/follow/get-min-followers?username='
export let FORGOT_PASSWORD = '/api/user/forgot-password?email='
export let CREATE_LESSION = '/api/user/create-lession'
export let GET_ONE_LESSION = '/api/user/get-one-lession?lession_id='
export let CREATE_COMMENT = "/api/comment/create"
export let GET_COMMENTS = "/api/comment/get-comments?blog_id="
export let GET_NOTIFICATIONS = '/api/user/notifications?user_id='
export let READ_NOTIFICATION = '/api/user/read-notification?notification_id='
export let GET_ALL_LESSONS = '/api/user/get-all-lessions?username='
export let DELETE_LESSON = '/api/user/delete-one-lession?lession_id='
export let UPDATE_LESSION = '/api/user/update-lession'
export let CREATE_STATUS = '/api/user/create-status'
export let GET_STATUS = '/api/user/get-status?user_id='